name: test file

on:
  push:
    branches:
      - "main"
jobs:
  insert-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: step name
        run: |
          echo "----- pushing to main directly"    